project_id = "divi-local"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "divi://auth/callback"
additional_redirect_urls = ["http://localhost:8083", "divi://auth/callback"]
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = true
max_frequency = "1m0s"
