import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from './theme';

export const appStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface },
  app: { flex: 1 },
  flex: { flex: 1 },
  page: { paddingHorizontal: spacing.lg, paddingTop: spacing.xl, paddingBottom: 130 },
  welcome: { flex: 1, backgroundColor: colors.brand, padding: spacing.lg },
  welcomeCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 20 },
  logoCircle: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeTitle: { color: '#FFFFFF', ...typography.display },
  welcomeCopy: {
    maxWidth: 360,
    textAlign: 'center',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 20,
    lineHeight: 29,
    fontWeight: '400',
  },
  welcomeActions: { gap: 22, paddingBottom: 20 },
  demoLink: { color: '#FFFFFF', textAlign: 'center', ...typography.headline },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  pageTitle: { color: colors.ink, ...typography.screenTitle },
  sectionTitle: { color: colors.ink, marginTop: 8, ...typography.sectionTitle },
  homeSectionTitle: { marginTop: spacing.xxl, marginBottom: spacing.sm },
  hero: {
    marginVertical: 28,
    backgroundColor: colors.brand,
    borderRadius: radii.xl,
    padding: 26,
    gap: 8,
  },
  detailHero: {
    backgroundColor: 'rgba(112, 207, 69, 0.94)',
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  detailHeroCopy: { flex: 1, minWidth: 0, gap: 4 },
  heroEyebrow: { color: 'rgba(255,255,255,0.86)', ...typography.caption, letterSpacing: 1.1 },
  heroAmount: { color: '#FFFFFF', ...typography.amount },
  heroCopy: { color: 'rgba(255,255,255,0.88)', ...typography.body },
  heroQrAction: {
    width: 96,
    alignItems: 'center',
    gap: 4,
  },
  heroQrCard: {
    padding: 6,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
  },
  heroQrLabel: { color: colors.surface, ...typography.caption },
  detailScrollContent: { paddingBottom: spacing.lg },
  listRow: {
    minHeight: 86,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
    paddingVertical: 18,
  },
  marker: { width: 9, height: 54, borderRadius: 5 },
  rowCopy: { flex: 1, gap: 4 },
  rowTitle: { color: colors.ink, ...typography.title },
  rowSub: { color: colors.secondary, ...typography.subheadline },
  rowValue: { color: colors.ink, ...typography.headline },
  warningText: { color: colors.warning },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 92,
    backgroundColor: '#FFFFFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.separator,
    flexDirection: 'row',
    paddingHorizontal: 6,
    paddingBottom: 8,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 5 },
  tabLabel: { color: colors.tertiary, fontSize: 10, fontWeight: '700' },
  tabActive: { color: colors.ink },
  createTab: { flex: 1.25, alignItems: 'center', top: -18, gap: 4 },
  createButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: '#FFFFFF',
  },
  header: {
    minHeight: 58,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  headerTitle: { maxWidth: '72%', color: colors.ink, ...typography.headline },
  centerPage: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 22 },
  centerCopy: { color: colors.secondary, textAlign: 'center', ...typography.body },
  bottomActions: { alignSelf: 'stretch', gap: 20, marginTop: 'auto', paddingBottom: 18 },
  secondaryLink: { color: colors.ink, textAlign: 'center', padding: 12, ...typography.headline },
  nameInput: {
    color: colors.ink,
    borderBottomWidth: 1,
    borderBottomColor: colors.separator,
    paddingVertical: 16,
    ...typography.sectionTitle,
  },
  receiptInstructions: {
    color: colors.secondary,
    marginTop: spacing.sm,
    ...typography.body,
  },
  receiptItemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  receiptItemsTitle: { color: colors.ink, ...typography.title },
  addItemButton: {
    minHeight: 40,
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 12,
    borderRadius: radii.pill,
    backgroundColor: colors.brandSoft,
    marginTop: spacing.md,
  },
  addItemLabel: { color: colors.brandDeep, ...typography.headline },
  emptyItems: {
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.xl,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
  },
  emptyItemsTitle: { color: colors.ink, ...typography.headline },
  receiptItemRow: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
    paddingVertical: 14,
  },
  swipeableItem: { position: 'relative', overflow: 'hidden' },
  swipeableItemContent: { backgroundColor: colors.surface },
  swipeDeleteAction: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 92,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    backgroundColor: colors.negative,
  },
  swipeDeleteLabel: { color: colors.surface, ...typography.caption },
  quantityBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.separator,
  },
  quantityBadgeText: { color: colors.ink, ...typography.headline },
  editItemButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.surfaceMuted,
  },
  itemEditor: {
    gap: 10,
    padding: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surfaceMuted,
    marginVertical: spacing.sm,
  },
  itemEditorHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  itemEditorTitle: { color: colors.ink, marginBottom: 2, ...typography.title },
  itemEditorDeleteButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.negativeSoft,
  },
  inputLabel: { color: colors.ink, ...typography.subheadline, fontWeight: '600' },
  itemInput: {
    minHeight: 52,
    color: colors.ink,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.separator,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
    ...typography.body,
  },
  itemInputRow: { flexDirection: 'row', gap: 12 },
  quantityField: { width: 110, gap: 8 },
  priceField: { flex: 1, gap: 8 },
  priceInputShell: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.separator,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
  },
  currencyPrefix: { color: colors.secondary, marginRight: 6, ...typography.body },
  priceInput: { flex: 1, color: colors.ink, paddingVertical: 0, ...typography.body },
  itemError: { color: colors.negative, ...typography.subheadline },
  itemEditorActions: { flexDirection: 'row', gap: 12, marginTop: spacing.sm },
  cancelItemButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.separator,
  },
  cancelItemLabel: { color: colors.ink, ...typography.headline },
  saveItemButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.brand,
  },
  saveItemLabel: { color: colors.surface, ...typography.headline },
  totalBlock: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: 18,
    marginVertical: 20,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 7,
  },
  editableTotalRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  editableTotalLabel: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: spacing.sm,
  },
  taxTipLabel: { color: colors.ink, ...typography.subheadline, fontWeight: '600' },
  taxTipPercentage: { color: colors.tertiary, ...typography.caption, fontWeight: '600' },
  totalInputShell: {
    width: 126,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surface,
    paddingHorizontal: 11,
  },
  totalInputPrefix: { color: colors.secondary, ...typography.headline },
  totalInput: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    textAlign: 'right',
    paddingVertical: 0,
    ...typography.headline,
  },
  namedAdjustmentRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  adjustmentNameInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surface,
    color: colors.ink,
    paddingHorizontal: 11,
    paddingVertical: 0,
    ...typography.subheadline,
  },
  namedAdjustmentAmount: { width: 116 },
  removeAdjustmentButton: {
    width: 36,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustmentActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  adjustmentButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 11,
    borderRadius: radii.pill,
    backgroundColor: colors.brandSoft,
  },
  negativeAdjustmentButton: { backgroundColor: colors.negativeSoft },
  adjustmentButtonLabel: { color: colors.brandDeep, ...typography.subheadline, fontWeight: '600' },
  negativeAdjustmentButtonLabel: { color: colors.negative },
  warning: { color: colors.warning, marginBottom: 18, ...typography.headline },
  listSection: { paddingHorizontal: 24 },
  claimItem: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  claimItemSummary: {
    minHeight: 86,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
  },
  claimItemDisclosure: {
    flex: 1,
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  claimantPanel: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    marginBottom: spacing.md,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
  },
  claimantPanelTitle: { color: colors.ink, ...typography.headline },
  participantRail: { gap: 12, paddingVertical: 12, paddingHorizontal: 2 },
  participantChoice: { width: 66, alignItems: 'center', gap: 5 },
  participantChoiceCircle: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.separator,
  },
  participantChoiceSelected: {
    backgroundColor: colors.brandSoft,
    borderColor: colors.brand,
  },
  participantChoiceInitial: { color: colors.secondary, ...typography.headline },
  participantChoiceLabel: { color: colors.secondary, ...typography.caption },
  participantChoiceLabelSelected: { color: colors.brandDeep },
  claimantRow: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 10 },
  claimantAvatar: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: colors.brandSoft,
  },
  claimantInitial: { color: colors.brandDeep, ...typography.caption },
  finalizeSection: {
    padding: spacing.lg,
    gap: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.separator,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
  },
  finalizeHint: { color: colors.secondary, textAlign: 'center', ...typography.subheadline },
  summaryPage: { paddingBottom: spacing.xxl },
  summaryHero: {
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: colors.brand,
  },
  summaryEyebrow: { color: 'rgba(255,255,255,0.86)', ...typography.headline },
  summaryAmount: { color: colors.surface, ...typography.amount },
  summaryCopy: { color: 'rgba(255,255,255,0.88)', ...typography.body },
  allocation: { padding: 24, gap: 18 },
  allocationItem: {
    gap: 12,
    paddingBottom: 22,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  qr: { backgroundColor: '#FFFFFF', padding: 20, borderRadius: radii.lg },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.4)' },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    padding: 28,
    gap: 18,
  },
  fallbackAmount: { color: colors.ink, textAlign: 'center', ...typography.amount },
  profileAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 24,
  },
  profileInitial: { color: '#FFFFFF', ...typography.screenTitle },
  signOut: { color: colors.negative, marginTop: 28, ...typography.headline },
});
